import React, { useState, useEffect } from 'react';import { useStore, uid, type OwnedBusiness } from '../lib/store';import { formatMoney, haptic, balanceInUsd } from '../lib/utils';import { JOBS, BUSINESSES } from '../lib/constants';
export default function CityScreen() { const {user,accounts,businesses,jobCooldowns,patchUser,updateBalance,addTx,addNotif,addBiz,setJobCD}=useStore();const [tab,setTab]=useState<'j'|'b'|'l'>('j');const [,tick]=useState(0);
useEffect(()=>{const i=setInterval(()=>tick(t=>t+1),1000);return()=>clearInterval(i)},[]);
if(!user)return null;const pa=accounts.find(a=>a.type==='personal');const xpMax=user.level*100;
const work=(j:typeof JOBS[number])=>{const cd=jobCooldowns[j.id]||0;if(Date.now()<cd||user.level<j.level||!pa)return haptic('error');haptic('success');updateBalance(pa.id,j.pay);const nx=user.xp+j.xp;const lu=nx>=xpMax;patchUser({xp:lu?nx-xpMax:nx,level:lu?user.level+1:user.level});setJobCD(j.id,Date.now()+j.cooldown*1000);addTx({id:uid(),from_user_id:0,to_user_id:user.telegram_id,from_account_id:'city',to_account_id:pa.id,amount:j.pay,fee:0,currency:'LNC',type:'job',status:'completed',created_at:new Date().toISOString()});if(lu)addNotif({id:uid(),title:'🎉 Level Up!',message:`LVL ${user.level+1}`,type:'system',read:false,created_at:new Date().toISOString()});};
const buyBiz=(b:typeof BUSINESSES[number])=>{if(user.level<b.level||!pa||pa.balance<b.cost)return haptic('error');haptic('success');updateBalance(pa.id,-b.cost);addBiz({id:uid(),type:b.id,name:b.name,income:b.income});addTx({id:uid(),from_user_id:user.telegram_id,to_user_id:0,from_account_id:pa.id,to_account_id:'city',amount:b.cost,fee:0,currency:'LNC',type:'business',status:'completed',created_at:new Date().toISOString()});};
const collect=(b:OwnedBusiness)=>{if(!pa)return;haptic('success');updateBalance(pa.id,b.income);addTx({id:uid(),from_user_id:0,to_user_id:user.telegram_id,from_account_id:'city',to_account_id:pa.id,amount:b.income,fee:0,currency:'LNC',type:'business',status:'completed',created_at:new Date().toISOString()});};
const lb=[{n:'CryptoKing',l:25,x:12500},{n:'TON_Master',l:22,x:11000},{n:'Luna_Pro',l:19,x:9500},{n:user.first_name,l:user.level,x:user.xp},{n:'DeFi_Lord',l:15,x:7500}].sort((a,b)=>b.l-a.l||b.x-a.x);
return(<div className="h-full overflow-y-auto pb-24 safe-top"><div className="px-5 pt-6">
<h1 className="text-2xl font-extrabold mb-1">🏙️ Luna City</h1><p className="text-sm text-white/30 mb-4">Зарабатывайте реальные LNC</p>
<div className="glass-accent rounded-2xl p-4 mb-4 animate-slide-up"><div className="flex items-center justify-between mb-2"><span className="font-bold">LVL {user.level}</span><span className="text-xs text-white/30">{user.xp}/{xpMax} XP</span></div><div className="h-2 bg-white/[0.06] rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-violet-500 to-pink-500 rounded-full transition-all" style={{width:`${Math.min(user.xp/xpMax*100,100)}%`}} /></div></div>
<div className="flex gap-2 mb-4">{([['j','💼 Работы'],['b','🏪 Бизнес'],['l','🏆 Рейтинг']] as const).map(([k,v])=><button key={k} onClick={()=>setTab(k)} className={`flex-1 py-2 rounded-xl text-sm font-semibold transition-all ${tab===k?'bg-white text-black':'glass text-white/50'}`}>{v}</button>)}</div>
{tab==='j'&&<div className="space-y-2.5 animate-fade-in">{JOBS.map(j=>{const cd=jobCooldowns[j.id]||0;const onCD=Date.now()<cd;const rem=Math.ceil((cd-Date.now())/1000);const locked=user.level<j.level;return(
<div key={j.id} className={`glass rounded-2xl p-4 ${locked?'opacity-30':''}`}><div className="flex items-center gap-3"><span className="text-2xl">{j.icon}</span><div className="flex-1"><p className="font-bold">{j.name}</p><p className="text-xs text-white/30">+◎{j.pay} · +{j.xp}XP · LVL{j.level}+</p></div>
<button onClick={()=>work(j)} disabled={onCD||locked} className={`px-4 py-2 rounded-xl text-sm font-semibold transition-all ${onCD||locked?'bg-white/5 text-white/25':'bg-white text-black active:scale-95'}`}>{locked?`🔒 ${j.level}`:onCD?`${rem}с`:'Работать'}</button></div></div>)})}</div>}
{tab==='b'&&<div className="space-y-2.5 animate-fade-in">{businesses.length>0&&<div className="mb-4"><p className="text-xs text-white/30 mb-2 font-medium">Мои бизнесы</p>{businesses.map(b=><div key={b.id} className="glass rounded-2xl p-4 flex items-center gap-3 mb-2"><span className="text-2xl">{BUSINESSES.find(x=>x.id===b.type)?.icon||'🏪'}</span><div className="flex-1"><p className="font-bold">{b.name}</p><p className="text-xs text-white/30">◎{b.income}/сбор</p></div><button onClick={()=>collect(b)} className="bg-white text-black px-4 py-2 rounded-xl text-sm font-semibold active:scale-95 transition-transform">Собрать</button></div>)}</div>}
<p className="text-xs text-white/30 mb-2 font-medium">Купить</p>{BUSINESSES.map(b=>{const locked=user.level<b.level;const owned=businesses.some(x=>x.type===b.id);return(
<div key={b.id} className={`glass rounded-2xl p-4 mb-2 ${locked||owned?'opacity-30':''}`}><div className="flex items-center gap-3"><span className="text-2xl">{b.icon}</span><div className="flex-1"><p className="font-bold">{b.name}</p><p className="text-xs text-white/30">◎{b.cost} · ◎{b.income}/сбор · LVL{b.level}</p></div>
<button onClick={()=>buyBiz(b)} disabled={locked||owned} className={`px-4 py-2 rounded-xl text-sm font-semibold ${owned?'bg-emerald-500/15 text-emerald-400':locked?'bg-white/5 text-white/25':'bg-white text-black active:scale-95'} transition-all`}>{owned?'✓':locked?`🔒 ${b.level}`:'Купить'}</button></div></div>)})}</div>}
{tab==='l'&&<div className="space-y-2 animate-fade-in">{lb.map((e,i)=><div key={i} className={`glass rounded-xl p-3 flex items-center gap-3 ${e.n===user.first_name?'ring-1 ring-violet-500/25':''}`}><span className="text-lg font-bold w-8 text-center tabular-nums">{i===0?'🥇':i===1?'🥈':i===2?'🥉':`${i+1}`}</span><p className="flex-1 font-medium text-sm">{e.n}</p><div className="text-right"><p className="text-sm font-bold">LVL {e.l}</p><p className="text-[11px] text-white/30">{e.x} XP</p></div></div>)}</div>}
</div></div>);}
