import React, { useState } from 'react';import { NEWS_ARTICLES } from '../lib/constants';import { haptic } from '../lib/utils';
export default function NewsScreen() { const [cat,setCat]=useState('all');const [sel,setSel]=useState<typeof NEWS_ARTICLES[number]|null>(null);
const cats=[{id:'all',l:'Все'},{id:'news',l:'Новости'},{id:'investments',l:'Инвестиции'},{id:'security',l:'Безопасность'},{id:'ecosystem',l:'Экосистема'}];
const list=cat==='all'?NEWS_ARTICLES:NEWS_ARTICLES.filter(a=>a.category===cat);
if(sel)return(<div className="h-full overflow-y-auto pb-24 safe-top"><div className="px-5 pt-4 pb-2 flex items-center gap-4"><button onClick={()=>setSel(null)} className="text-white/50 text-sm">← Назад</button></div><div className="px-5 mt-2 animate-fade-in"><div className="glass rounded-2xl p-5"><div className="flex items-center gap-2 mb-3"><span className="text-[11px] bg-white/8 px-2 py-0.5 rounded-lg">{sel.category}</span><span className="text-[11px] text-white/25">{sel.date}</span><span className="text-[11px] text-white/25">👁 {sel.views}</span></div><h2 className="text-xl font-extrabold mb-4">{sel.title}</h2><div className="text-[13px] text-white/60 leading-relaxed whitespace-pre-line">{sel.content}</div></div></div></div>);
return(<div className="h-full overflow-y-auto pb-24 safe-top"><div className="px-5 pt-6"><h1 className="text-2xl font-extrabold mb-4">📰 Витрина</h1>
<div className="flex gap-2 mb-4 overflow-x-auto pb-1">{cats.map(c=><button key={c.id} onClick={()=>{haptic('light');setCat(c.id)}} className={`px-4 py-2 rounded-xl text-sm font-semibold whitespace-nowrap transition-all ${cat===c.id?'bg-white text-black':'glass text-white/50'}`}>{c.l}</button>)}</div>
<div className="space-y-3">{list.map((a,i)=><button key={a.id} onClick={()=>{haptic('light');setSel(a)}} className="w-full glass rounded-2xl p-4 text-left animate-slide-up active:scale-[0.98] transition-all" style={{animationDelay:`${i*0.05}s`}}>
<div className="flex items-center gap-2 mb-2"><span className="text-[11px] bg-white/8 px-2 py-0.5 rounded-lg">{a.category}</span><span className="text-[11px] text-white/20">{a.date}</span></div>
<h3 className="font-bold mb-1">{a.title}</h3><p className="text-sm text-white/35 line-clamp-2">{a.summary}</p><span className="text-[11px] text-white/20 mt-2 block">👁 {a.views}</span></button>)}</div></div></div>);}
