import React, { useState } from 'react';import { useStore, uid, genAccNum, genIBAN } from '../lib/store';import { haptic, shortAddr } from '../lib/utils';
const W=[{id:'tonkeeper',n:'Tonkeeper',i:'💎',c:'#0098EA'},{id:'mytonwallet',n:'MyTonWallet',i:'🟦',c:'#3B82F6'},{id:'wallet',n:'Wallet',i:'📱',c:'#8B5CF6'},{id:'tonhub',n:'Tonhub',i:'🔷',c:'#0EA5E9'}];
export default function TonConnectScreen() { const {user,tonWallet,go,setTonWallet,addAccount,accounts,addNotif}=useStore();const [busy,setBusy]=useState(false);const [sw,setSw]=useState<string|null>(null);
if(!user)return null;
const connect=(wid:string)=>{haptic('medium');setSw(wid);setBusy(true);setTimeout(()=>{const addr='EQ'+Array.from({length:46},()=>'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'[Math.floor(Math.random()*62)]).join('');setTonWallet(addr);
[{t:'ton' as const,n:'TON',c:'TON' as const},{t:'usdt' as const,n:'USDT',c:'USDT' as const},{t:'bitcoin' as const,n:'Bitcoin',c:'BTC' as const},{t:'ethereum' as const,n:'Ethereum',c:'ETH' as const}].forEach(x=>{if(!accounts.find(a=>a.type===x.t))addAccount({id:uid(),user_id:user.telegram_id,type:x.t,name:x.n,currency:x.c,balance:0,account_number:genAccNum(),iban:genIBAN(),created_at:new Date().toISOString(),wallet_address:addr})});
addNotif({id:uid(),title:'🔗 Кошелёк подключён',message:W.find(w=>w.id===wid)?.n+' OK',type:'system',read:false,created_at:new Date().toISOString()});setBusy(false);},2000);};
return(<div className="h-full overflow-y-auto pb-24 safe-top"><div className="px-5 pt-4 pb-2 flex items-center gap-4"><button onClick={()=>go('profile')} className="text-white/50 text-sm">← Назад</button><h1 className="font-bold flex-1">TON Connect</h1></div>
<div className="px-5 mt-4">{tonWallet?<div className="animate-fade-in"><div className="glass-accent rounded-2xl p-5 text-center mb-6"><div className="w-16 h-16 rounded-full bg-emerald-500/15 flex items-center justify-center text-3xl mx-auto mb-4">✅</div><h3 className="font-bold text-lg mb-1">Подключён</h3><p className="text-sm text-white/35 tabular-nums">{shortAddr(tonWallet)}</p><button onClick={()=>{navigator.clipboard.writeText(tonWallet);haptic('light')}} className="text-xs text-white/25 mt-2">Копировать 📋</button></div>
<button onClick={()=>{haptic('medium');setTonWallet(null)}} className="btn-secondary w-full text-red-400">Отключить</button></div>:busy?<div className="flex flex-col items-center justify-center py-20 animate-fade-in"><div className="w-16 h-16 border-4 border-white/10 border-t-white rounded-full animate-spin mb-6" /><h3 className="font-bold text-lg mb-2">Подключение...</h3><p className="text-sm text-white/35">{W.find(w=>w.id===sw)?.n}</p></div>:
<div className="animate-fade-in"><div className="text-center mb-8"><span className="text-6xl block mb-4 animate-float">🔗</span><h2 className="text-xl font-extrabold mb-2">Подключите кошелёк</h2><p className="text-sm text-white/35">Выберите TON-кошелёк</p></div>
<div className="space-y-3">{W.map(w=><button key={w.id} onClick={()=>connect(w.id)} className="w-full glass rounded-2xl p-4 flex items-center gap-4 active:scale-[0.98] transition-all"><div className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl" style={{background:w.c+'15'}}>{w.i}</div><p className="flex-1 text-left font-bold">{w.n}</p><span className="text-white/15">›</span></button>)}</div></div>}</div></div>);}
