import React, { useState, useRef, useEffect } from 'react';import { useStore, uid } from '../lib/store';import { haptic } from '../lib/utils';
const AI:Record<string,string>={перевод:'📤 Перевод: Главная → Перевод → @username → сумма → подтвердить.\nКомиссия: Free 0.5%, Plus 0.3%, Cosmic 0%.',счёт:'🏦 Счета → + Открыть → тип → данные → подпись → PDF договор.',ton:'🔗 Профиль → TON-кошелёк → выбрать → подключить → авто-создание крипто-счетов.',kyc:'🔐 Профиль → KYC → 6 шагов → лимиты $50K/мес.',карта:'💳 Страница счёта → Оформить карту. Виртуальная $0, Премиум $4.99, Пластик $19.99.',комиссия:'💰 Free 0.5%, Plus 0.3%, Cosmic 0%. Автоматически от суммы.',кэшбэк:'💎 Free 0%, Plus 1%, Cosmic 3%.',безопасность:'🛡️ PIN + SHA-256 + биометрия + логирование.',lnc:'◎ 1 LNC = $0.05. Для переводов, подписок, покупок.'};
const QQ=['Как перевести?','Как открыть счёт?','Что такое LNC?','Какие комиссии?'];
export default function ChatScreen() { const {aiMsgs,supportMsgs,addAiMsg,addSupportMsg}=useStore();const [tab,setTab]=useState<'ai'|'sup'>('ai');const [inp,setInp]=useState('');const ref=useRef<HTMLDivElement>(null);
const msgs=tab==='ai'?aiMsgs:supportMsgs;const add=tab==='ai'?addAiMsg:addSupportMsg;
useEffect(()=>{ref.current?.scrollIntoView({behavior:'smooth'})},[msgs]);
const send=(t?:string)=>{const m=t||inp.trim();if(!m)return;haptic('light');setInp('');add({id:uid(),role:'user',content:m,timestamp:new Date().toISOString()});
setTimeout(()=>{if(tab==='ai'){const lo=m.toLowerCase();let r='🤔 Спросите про: переводы, счета, TON, KYC, карты, комиссии, LNC, безопасность.';for(const[k,v]of Object.entries(AI))if(lo.includes(k)){r=v;break;}add({id:uid(),role:'assistant',content:r,timestamp:new Date().toISOString()});}else{add({id:uid(),role:'assistant',content:'🤖 Сейчас позову оператора...',timestamp:new Date().toISOString()});setTimeout(()=>{add({id:uid(),role:'system',content:'⏳ Операторы заняты. FAQ: Профиль → FAQ',timestamp:new Date().toISOString()})},2000);}},800);};
return(<div className="h-full flex flex-col bg-black safe-top"><div className="px-5 pt-4 pb-2"><h1 className="text-2xl font-extrabold mb-3">💬 Чаты</h1>
<div className="flex gap-2">{(['ai','sup'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`flex-1 py-2.5 rounded-xl text-sm font-semibold transition-all ${tab===t?'bg-white text-black':'glass text-white/50'}`}>{t==='ai'?'🤖 Luna AI':'💬 Поддержка'}</button>)}</div></div>
<div className="flex-1 overflow-y-auto px-5 py-4 space-y-3">{msgs.length===0&&<div className="text-center py-10 animate-fade-in"><span className="text-5xl mb-4 block">{tab==='ai'?'🤖':'💬'}</span><h3 className="font-bold mb-2">{tab==='ai'?'Luna AI':'Поддержка'}</h3><p className="text-sm text-white/35 mb-4">{tab==='ai'?'Задайте вопрос!':'Опишите проблему'}</p>
{tab==='ai'&&<div className="flex flex-wrap gap-2 justify-center">{QQ.map(q=><button key={q} onClick={()=>send(q)} className="glass rounded-xl px-3 py-2 text-xs text-white/50 active:scale-95 transition-transform">{q}</button>)}</div>}</div>}
{msgs.map(m=><div key={m.id} className={`flex ${m.role==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-[13px] ${m.role==='user'?'bg-white text-black rounded-br-sm':m.role==='system'?'bg-amber-500/10 text-amber-400 border border-amber-500/15':'glass rounded-bl-sm'}`}>
<p className="whitespace-pre-line">{m.content}</p><p className={`text-[10px] mt-1 ${m.role==='user'?'text-black/35':'text-white/25'}`}>{new Date(m.timestamp).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</p></div></div>)}<div ref={ref} /></div>
<div className="px-5 pb-24 pt-2"><div className="glass rounded-2xl flex items-center px-4 gap-3"><input type="text" value={inp} onChange={e=>setInp(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Сообщение..." className="flex-1 bg-transparent py-3 text-white outline-none text-sm" /><button onClick={()=>send()} disabled={!inp.trim()} className="text-white/50 disabled:text-white/15 text-lg">➤</button></div></div></div>);}
