import React, { useState } from 'react';import { useStore } from '../lib/store';import { haptic, hashPin } from '../lib/utils';import PinPad from '../components/PinPad';
export default function SettingsScreen() { const {user,go,patchUser}=useStore();const [cp,setCp]=useState(false);const [ps,setPs]=useState<'cur'|'n1'|'n2'>('cur');const [np,setNp]=useState('');const [pe,setPe]=useState(false);
if(!user)return null;
const curPin=async(p:string)=>{const h=await hashPin(p,String(user.telegram_id));if(h===user.pin_hash){haptic('success');setPs('n1')}else{setPe(true);setTimeout(()=>setPe(false),600)}};
const np1=(p:string)=>{setNp(p);setPs('n2')};
const np2=async(p:string)=>{if(p!==np){setPe(true);setTimeout(()=>{setPe(false);setPs('n1');setNp('')},1000);return;}haptic('success');const h=await hashPin(p,String(user.telegram_id));patchUser({pin_hash:h});setCp(false);setPs('cur')};
if(cp)return(<div className="h-full bg-black safe-top"><div className="px-5 pt-4 pb-2 flex items-center gap-4"><button onClick={()=>{setCp(false);setPs('cur')}} className="text-white/50 text-sm">← Назад</button><h1 className="font-bold flex-1">Смена PIN</h1></div><PinPad title={ps==='cur'?'Текущий PIN':ps==='n1'?'Новый PIN':'Повторите'} onComplete={ps==='cur'?curPin:ps==='n1'?np1:np2} error={pe} /></div>);
return(<div className="h-full overflow-y-auto pb-24 safe-top"><div className="px-5 pt-4 pb-2 flex items-center gap-4"><button onClick={()=>go('profile')} className="text-white/50 text-sm">← Назад</button><h1 className="font-bold flex-1">Безопасность</h1></div>
<div className="px-5 mt-4 space-y-3">
<button onClick={()=>{haptic('light');setCp(true)}} className="w-full glass rounded-2xl p-4 flex items-center gap-4 text-left active:scale-[0.98] transition-transform"><span className="text-2xl">🔑</span><div className="flex-1"><p className="font-semibold">Сменить PIN</p><p className="text-xs text-white/30">4-значный код</p></div></button>
<button onClick={()=>{haptic('light');patchUser({biometrics_enabled:!user.biometrics_enabled})}} className="w-full glass rounded-2xl p-4 flex items-center gap-4 text-left active:scale-[0.98] transition-transform"><span className="text-2xl">🔒</span><div className="flex-1"><p className="font-semibold">Биометрия</p><p className="text-xs text-white/30">{user.biometrics_enabled?'Включена':'Выключена'}</p></div>
<div className={`w-12 h-7 rounded-full flex items-center px-1 transition-all ${user.biometrics_enabled?'bg-emerald-500':'bg-white/10'}`}><div className={`w-5 h-5 rounded-full bg-white transition-transform ${user.biometrics_enabled?'translate-x-5':''}`} /></div></button>
</div></div>);}
